"""
Parallel Runner — executes Wave 1 agents simultaneously using ThreadPoolExecutor.
Each agent gets a deep copy of credit_state to avoid thread conflicts.
Results are merged back into the main state after all agents complete.
"""

import copy
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime


# Maps agent name → the credit_state key it writes to
AGENT_OUTPUT_KEYS = {
    "Financial Analyst": "financial_analysis",
    "EBITDA Analyst":    "ebitda_analysis",
    "Commercial Analyst":"commercial_analysis",
    "Legal Analyst":     "legal_analysis",
}


def run_parallel_wave(
    agents: list,
    credit_state: dict,
    on_agent_complete=None,
) -> dict:
    """
    Run a list of agents in parallel.

    Each agent:
    1. Receives a deep copy of credit_state (no shared mutable state)
    2. Runs independently in its own thread
    3. Returns its updated state copy

    Results are merged back: only the agent's designated output key
    is written to the main state, preventing overwrites.
    """
    def _run(agent):
        state_copy = copy.deepcopy(credit_state)
        result_state = agent.run(state_copy)
        return agent.name, result_state

    completed_order = []

    with ThreadPoolExecutor(max_workers=len(agents)) as executor:
        future_to_agent = {executor.submit(_run, agent): agent for agent in agents}

        for future in as_completed(future_to_agent):
            agent_name, result_state = future.result()
            completed_order.append(agent_name)

            # Merge only this agent's output key
            output_key = AGENT_OUTPUT_KEYS.get(agent_name)
            if output_key and output_key in result_state:
                credit_state[output_key] = result_state[output_key]

            # Merge alerts generated by this agent
            for alert in result_state.get("human_alerts", []):
                if alert not in credit_state["human_alerts"]:
                    credit_state["human_alerts"].append(alert)

            # Merge agent log entries
            for log_entry in result_state.get("agent_log", []):
                if log_entry not in credit_state["agent_log"]:
                    credit_state["agent_log"].append(log_entry)

            if on_agent_complete:
                on_agent_complete(agent_name, credit_state)

    return credit_state
