"""
CreditMind FastAPI Backend
Owner: John Hanish

Bridge between Peter's Python agents (core/) and Abraham's Next.js frontend.
Run: uvicorn api.main:app --reload --port 8000
"""

import json
import copy
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from datetime import datetime

from core.orchestrator import (
    run_full_underwriting,
    DailyMonitoringOrchestrator,
    QuarterlyReviewOrchestrator,
)
from core.credit_state import create_credit_state
from core.alert_system import get_pending_alerts, resolve_alert, get_alert_summary
from agents.ic_memo_writer import ICMemoWriterAgent

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(title="CreditMind API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "https://frontend-chi-lac-14.vercel.app",
        "https://creditmind-production.up.railway.app",
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory portfolio store (replaces Streamlit session_state for API context)
_portfolio: dict[str, dict] = {}

# Sector-level alerts generated by refresh
_sector_alerts: list[dict] = []

# Refresh state — tracks whether a background refresh is running
_refresh_state: dict = {"running": False, "last_run": None, "last_error": None}

# Sector keyword config (from Jasmin's data file)
_NEWS_SOURCES_PATH = Path(__file__).parent.parent / "data" / "news_sources.json"
try:
    with open(_NEWS_SOURCES_PATH) as f:
        _SECTOR_KEYWORDS: dict = json.load(f).get("sector_news_config", {})
except Exception:
    _SECTOR_KEYWORDS = {}

# Mapping from portfolio sector names → news_sources.json keys
_SECTOR_MAP = {
    "Aerospace & Defense":   "Industrials",
    "Healthcare":            "Health Care",
    "Health Care":           "Health Care",
    "Energy":                "Energy",
    "Materials":             "Materials",
    "Industrials":           "Industrials",
    "Consumer Discretionary":"Consumer Discretionary",
    "Consumer Staples":      "Consumer Staples",
    "Financials":            "Financials",
    "Information Technology":"Information Technology",
    "Technology":            "Information Technology",
    "Communication Services":"Communication Services",
    "Utilities":             "Utilities",
    "Real Estate":           "Real Estate",
}

# Seed the 50-company demo portfolio on startup
from data.seed_portfolio import DEMO_PORTFOLIO
for _deal in DEMO_PORTFOLIO:
    _portfolio[_deal["deal_id"]] = _deal


def _get_deal(deal_id: str) -> dict:
    deal = _portfolio.get(deal_id)
    if not deal:
        raise HTTPException(status_code=404, detail=f"Deal '{deal_id}' not found.")
    return deal


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class UnderwriteRequest(BaseModel):
    company: str
    ticker: str
    loan_amount: float
    loan_tenor: int
    loan_type: str
    sponsor: str


class MonitorRequest(BaseModel):
    deal_id: str
    ticker: str


class QuarterlyReviewRequest(BaseModel):
    deal_id: str
    ticker: str


class CreditMemoRequest(BaseModel):
    deal_id: str


class ResolveAlertRequest(BaseModel):
    alert_id: str
    resolved_by: str
    notes: Optional[str] = ""


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class MonitorResponse(BaseModel):
    deal_id: str
    risk_score: Optional[float]
    alerts: list
    sentiment: Optional[dict]
    monitoring_summary: Optional[str]
    early_warning_flags: Optional[list]
    news_signals: Optional[list]
    job_signals: Optional[dict]
    consumer_signals: Optional[dict]


class QuarterlyReviewResponse(BaseModel):
    deal_id: str
    rating: Optional[str]
    covenant_status: Optional[dict]
    rating_change: Optional[str]
    review_summary: Optional[str]


class CreditMemoResponse(BaseModel):
    deal_id: str
    memo_sections: Optional[dict]
    recommendation: Optional[str]
    approval_status: Optional[str]


class AlertSummary(BaseModel):
    critical: int
    high: int
    medium: int
    low: int


class AlertsResponse(BaseModel):
    alerts: list
    summary: AlertSummary


class ResolveAlertResponse(BaseModel):
    success: bool
    alert_id: str
    resolved_at: str


# ---------------------------------------------------------------------------
# Original 6 Endpoints
# ---------------------------------------------------------------------------

@app.post("/api/underwrite")
def underwrite(req: UnderwriteRequest):
    """Run full credit underwriting pipeline. Returns full credit_state dict."""
    try:
        credit_state = run_full_underwriting(
            company=req.company,
            ticker=req.ticker,
            loan_amount=req.loan_amount,
            loan_tenor=req.loan_tenor,
            loan_type=req.loan_type,
        )
        deal_id = credit_state.get("deal_id", f"{req.ticker}_{int(datetime.now().timestamp())}")
        credit_state["deal_id"] = deal_id
        _portfolio[deal_id] = credit_state
        return credit_state
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/daily-monitor", response_model=MonitorResponse)
def daily_monitor(req: MonitorRequest):
    """Run daily monitoring agents for an existing deal."""
    try:
        credit_state = _get_deal(req.deal_id)
        orchestrator = DailyMonitoringOrchestrator()
        credit_state = orchestrator.run(credit_state)
        _portfolio[req.deal_id] = credit_state

        summary = get_alert_summary(credit_state)
        return MonitorResponse(
            deal_id=req.deal_id,
            risk_score=credit_state.get("risk_score"),
            alerts=get_pending_alerts(credit_state),
            sentiment=credit_state.get("sentiment_analysis"),
            monitoring_summary=credit_state.get("early_warning_summary"),
            early_warning_flags=credit_state.get("early_warning_flags", []),
            news_signals=credit_state.get("news_signals", []),
            job_signals=credit_state.get("job_signals"),
            consumer_signals=credit_state.get("consumer_signals"),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/quarterly-review", response_model=QuarterlyReviewResponse)
def quarterly_review(req: QuarterlyReviewRequest):
    """Run quarterly review agents for an existing deal."""
    try:
        credit_state = _get_deal(req.deal_id)
        orchestrator = QuarterlyReviewOrchestrator()
        credit_state = orchestrator.run(credit_state)
        _portfolio[req.deal_id] = credit_state

        return QuarterlyReviewResponse(
            deal_id=req.deal_id,
            rating=credit_state.get("credit_rating"),
            covenant_status=credit_state.get("covenant_status"),
            rating_change=credit_state.get("rating_change"),
            review_summary=credit_state.get("quarterly_review_summary"),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/credit-memo", response_model=CreditMemoResponse)
def credit_memo(req: CreditMemoRequest):
    """Generate IC credit memo for an existing deal."""
    try:
        credit_state = _get_deal(req.deal_id)
        agent = ICMemoWriterAgent()
        credit_state = agent.run(credit_state)
        _portfolio[req.deal_id] = credit_state

        return CreditMemoResponse(
            deal_id=req.deal_id,
            memo_sections=credit_state.get("ic_memo"),
            recommendation=credit_state.get("recommendation"),
            approval_status=credit_state.get("approval_status"),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.get("/api/alerts", response_model=AlertsResponse)
def get_alerts():
    """Return all pending alerts — company-level from portfolio + sector-level from last refresh."""
    try:
        all_alerts = []
        summary = {"critical": 0, "high": 0, "medium": 0, "low": 0}

        # Company-level alerts from individual deals
        for deal in _portfolio.values():
            pending = get_pending_alerts(deal)
            for alert in pending:
                alert["_deal_id"] = deal.get("deal_id", "")
                alert["_company"] = deal.get("company", "Unknown")
                all_alerts.append(alert)
                sev = alert.get("severity", "LOW").lower()
                if sev in summary:
                    summary[sev] += 1

        # Sector-level alerts from last refresh
        for alert in _sector_alerts:
            if not alert.get("resolved", False):
                all_alerts.append(alert)
                sev = alert.get("severity", "LOW").lower()
                if sev in summary:
                    summary[sev] += 1

        return AlertsResponse(alerts=all_alerts, summary=AlertSummary(**summary))
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/alerts/resolve", response_model=ResolveAlertResponse)
def resolve_alert_endpoint(req: ResolveAlertRequest):
    """Resolve an alert by alert_id across the portfolio."""
    try:
        for deal in _portfolio.values():
            alerts = deal.get("human_alerts", [])
            for i, alert in enumerate(alerts):
                if alert.get("alert_id") == req.alert_id or str(i) == req.alert_id:
                    resolve_alert(deal, i, req.resolved_by)
                    _portfolio[deal["deal_id"]] = deal
                    return ResolveAlertResponse(
                        success=True,
                        alert_id=req.alert_id,
                        resolved_at=datetime.now().isoformat(),
                    )
        raise HTTPException(status_code=404, detail=f"Alert '{req.alert_id}' not found.")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


# ---------------------------------------------------------------------------
# 6 Sector Intelligence Endpoints
# NOTE: Stubbed — depends on Peter's run_sector_intelligence() (not yet implemented).
# Returns valid JSON with status="not_implemented" so Abraham's frontend can build against the shape.
# ---------------------------------------------------------------------------

@app.get("/api/sector/heat-map")
def sector_heat_map():
    return {
        "status": "not_implemented",
        "sectors": [],
        "time_series": [],
        "forecast": [],
        "portfolio_overlays": [],
    }


@app.get("/api/sector/contagion/{sector_id}")
def sector_contagion(sector_id: str):
    return {
        "status": "not_implemented",
        "sector_id": sector_id,
        "event_summary": "",
        "affected_loans": [],
    }


@app.get("/api/sector/forecast")
def sector_forecast():
    return {
        "status": "not_implemented",
        "forecast_horizon_days": 30,
        "sectors": [],
    }


@app.get("/api/sector/impact-brief/{deal_id}")
def sector_impact_brief(deal_id: str):
    _get_deal(deal_id)  # validate deal exists
    return {
        "status": "not_implemented",
        "deal_id": deal_id,
        "company": _portfolio[deal_id].get("company", ""),
        "sector_tags": [],
        "sector_stress_score": None,
        "active_sector_alerts": [],
        "contagion_flags": [],
    }


@app.get("/api/portfolio/sector-map")
def portfolio_sector_map():
    deals = [
        {
            "deal_id":         d.get("deal_id"),
            "company":         d.get("company"),
            "sector":          d.get("sector", ""),
            "loan_amount":     d.get("loan_amount", 0),
            "internal_rating": d.get("internal_rating"),
            "risk_score":      d.get("live_risk_score", d.get("risk_score")),
            "loan_status":     d.get("loan_status"),
        }
        for d in _portfolio.values()
    ]
    return {"deals": deals}


@app.get("/api/alerts/sector")
def sector_alerts():
    """Return live sector alerts generated by the last refresh."""
    return {"sector_alerts": _sector_alerts}


# ---------------------------------------------------------------------------
# 7. Sector Refresh — runs monitoring agents across all portfolio sectors
# ---------------------------------------------------------------------------

def _run_sector_monitoring():
    """Background task: run NewsIntelligence + EarlyWarning for every sector in portfolio."""
    from agents.news_intelligence import NewsIntelligenceAgent
    from agents.early_warning import EarlyWarningAgent
    from core.credit_state import add_alert

    _refresh_state["running"] = True
    _refresh_state["last_error"] = None

    try:
        # Group portfolio deals by sector
        sector_deals: dict[str, list] = {}
        for deal in _portfolio.values():
            raw_sector = deal.get("sector", "")
            mapped = _SECTOR_MAP.get(raw_sector, raw_sector)
            if mapped not in sector_deals:
                sector_deals[mapped] = []
            sector_deals[mapped].append(deal)

        new_sector_alerts = []

        def _monitor_one_sector(sector_name: str, deals: list) -> list:
            keywords = _SECTOR_KEYWORDS.get(sector_name, {}).get("keywords", [sector_name])
            sector_state = {
                "sector": sector_name,
                "keywords": keywords,
                "deals_in_sector": [
                    {
                        "deal_id":       d.get("deal_id"),
                        "company":       d.get("company"),
                        "internal_rating": d.get("internal_rating"),
                        "loan_amount":   d.get("loan_amount", 0),
                        "risk_score":    d.get("live_risk_score", d.get("risk_score", 50)),
                    }
                    for d in deals
                ],
                "human_alerts": [],
                "news_signals": [],
                "agent_log": [],
            }

            # Run news intel first, then early warning uses its output
            news_agent = NewsIntelligenceAgent()
            sector_state = news_agent.run_sector(sector_state)

            ew_agent = EarlyWarningAgent()
            sector_state = ew_agent.run_sector(sector_state)

            # Tag alerts with sector metadata and unique IDs
            alerts = []
            for i, alert in enumerate(sector_state.get("human_alerts", [])):
                alerts.append({
                    **alert,
                    "alert_id":   f"sector-{sector_name[:6].lower().replace(' ', '')}-{int(datetime.now().timestamp())}-{i}",
                    "sector_id":  sector_name,
                    "alert_type": "sector",
                    "company":    f"{sector_name} Sector",
                    "message":    alert.get("trigger", ""),
                })
            return alerts

        # Run all sectors in parallel
        with ThreadPoolExecutor(max_workers=6) as executor:
            futures = {
                executor.submit(_monitor_one_sector, sector, deals): sector
                for sector, deals in sector_deals.items()
                if deals  # only sectors that have deals
            }
            for future in as_completed(futures):
                try:
                    new_sector_alerts.extend(future.result())
                except Exception as e:
                    sector = futures[future]
                    new_sector_alerts.append({
                        "alert_id":   f"sector-error-{int(datetime.now().timestamp())}",
                        "sector_id":  sector,
                        "alert_type": "sector",
                        "company":    f"{sector} Sector",
                        "severity":   "LOW",
                        "message":    f"Monitoring check failed: {str(e)}",
                        "timestamp":  datetime.now().isoformat(),
                        "resolved":   False,
                    })

        # Replace sector alerts with fresh results
        _sector_alerts.clear()
        _sector_alerts.extend(new_sector_alerts)
        _refresh_state["last_run"] = datetime.now().isoformat()

    except Exception as e:
        _refresh_state["last_error"] = str(e)
    finally:
        _refresh_state["running"] = False


@app.post("/api/refresh-alerts")
def refresh_alerts():
    """Trigger sector-level monitoring agents across the entire portfolio.
    Runs in background — returns immediately. Poll /api/refresh-status to check progress."""
    if _refresh_state["running"]:
        return {
            "status": "already_running",
            "message": "A refresh is already in progress.",
            "last_run": _refresh_state["last_run"],
        }
    thread = threading.Thread(target=_run_sector_monitoring, daemon=True)
    thread.start()
    return {
        "status": "started",
        "message": "Sector monitoring agents are running. Poll /api/refresh-status for completion.",
        "sectors": len(set(_SECTOR_MAP.get(d.get("sector", ""), d.get("sector", "")) for d in _portfolio.values())),
    }


@app.get("/api/refresh-status")
def refresh_status():
    """Check whether a refresh is running and when the last one completed."""
    return {
        "running":    _refresh_state["running"],
        "last_run":   _refresh_state["last_run"],
        "last_error": _refresh_state["last_error"],
        "alert_count": len(_sector_alerts),
    }
