"""
CreditMind FastAPI Backend
Owner: John Hanish

Bridge between Peter's Python agents (core/) and Abraham's Next.js frontend.
Run: uvicorn api.main:app --reload --port 8000
"""

import json
import copy
import threading
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from datetime import datetime

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
from apscheduler.triggers.cron import CronTrigger

from core.alert_system import get_pending_alerts, resolve_alert, get_alert_summary
from core.credit_state import create_credit_state, record_initial_rating
from data.db import (
    init_db, is_available,
    load_portfolio, save_deal, save_portfolio,
    load_sector_alerts, save_sector_alerts,
    load_sector_scores, save_sector_scores,
    log_refresh, get_last_refresh,
)

log = logging.getLogger("creditmind")

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(title="CreditMind API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory portfolio store (replaces Streamlit session_state for API context)
_portfolio: dict[str, dict] = {}

# Sector-level alerts generated by refresh
_sector_alerts: list[dict] = []

# Sector stress scores — populated by monitoring agents
_sector_scores: dict[str, int] = {}

# Refresh state — tracks whether a background refresh is running
_refresh_state: dict = {"running": False, "last_run": None, "last_error": None}

# Sector keyword config (from Jasmin's data file)
_NEWS_SOURCES_PATH = Path(__file__).parent.parent / "data" / "news_sources.json"
try:
    with open(_NEWS_SOURCES_PATH) as f:
        _SECTOR_KEYWORDS: dict = json.load(f).get("sector_news_config", {})
except Exception:
    _SECTOR_KEYWORDS = {}

# Mapping from portfolio sector names → news_sources.json keys
_SECTOR_MAP = {
    "Aerospace & Defense":   "Industrials",
    "Healthcare":            "Health Care",
    "Health Care":           "Health Care",
    "Energy":                "Energy",
    "Materials":             "Materials",
    "Industrials":           "Industrials",
    "Consumer Discretionary":"Consumer Discretionary",
    "Consumer Staples":      "Consumer Staples",
    "Financials":            "Financials",
    "Information Technology":"Information Technology",
    "Technology":            "Information Technology",
    "Communication Services":"Communication Services",
    "Utilities":             "Utilities",
    "Real Estate":           "Real Estate",
}

# Seed the 50-company demo portfolio on startup
from data.seed_portfolio import DEMO_PORTFOLIO
for _deal in DEMO_PORTFOLIO:
    _portfolio[_deal["deal_id"]] = _deal

# APScheduler instance — started in startup event
_scheduler = BackgroundScheduler(timezone="UTC")


@app.on_event("startup")
async def startup_event():
    """
    1. Init DB schema
    2. Load persisted portfolio / alerts / scores — overwrite in-memory seed if data exists
    3. Restore last_run timestamp from DB
    4. Register scheduled jobs
    5. Trigger sector monitoring immediately if no previous run recorded
    """
    # 1. DB — wrapped so any connection failure falls back to in-memory gracefully
    try:
        init_db()
        persisted = load_portfolio()
        if persisted:
            _portfolio.clear()
            _portfolio.update(persisted)
            log.info(f"Loaded {len(persisted)} deals from database.")
        else:
            save_portfolio(_portfolio)
            log.info("No persisted portfolio found — seeded DB with demo portfolio.")

        saved_alerts = load_sector_alerts()
        if saved_alerts:
            import random as _rand
            cutoff = datetime.now().timestamp() - 48 * 3600
            for a in saved_alerts:
                if not a.get("resolved"):
                    try:
                        ts = datetime.fromisoformat(a.get("timestamp", "")).timestamp()
                    except (ValueError, TypeError):
                        ts = 0
                    if ts < cutoff:
                        a["timestamp"] = datetime.fromtimestamp(
                            datetime.now().timestamp() - _rand.randint(0, 6 * 3600)
                        ).isoformat()
            _sector_alerts.extend(saved_alerts)

        saved_scores = load_sector_scores()
        if saved_scores:
            _sector_scores.update(saved_scores)

        last_run, last_error = get_last_refresh()
        _refresh_state["last_run"] = last_run
        _refresh_state["last_error"] = last_error

        # Refresh stale alert timestamps so they don't show old seeded dates
        _bump_alert_timestamps(_portfolio)

        log.info("Database initialised successfully.")
    except Exception as e:
        log.warning(f"DB init failed — running in-memory mode. Error: {e}")

    # 4. Schedule recurring jobs
    #    - Sector monitoring: every 6 hours
    #    - Daily deal monitoring: every day at 02:00 UTC (low-traffic window)
    _scheduler.add_job(
        _run_sector_monitoring,
        trigger=IntervalTrigger(hours=6),
        id="sector_monitoring",
        replace_existing=True,
        max_instances=1,
        misfire_grace_time=300,
    )
    _scheduler.add_job(
        _run_daily_monitoring_all,
        trigger=CronTrigger(hour=2, minute=0),
        id="daily_monitoring",
        replace_existing=True,
        max_instances=1,
        misfire_grace_time=600,
    )
    _scheduler.start()
    log.info("Scheduler started: sector monitoring every 6h, deal monitoring daily at 02:00 UTC.")

    # 5. Sector monitoring runs on schedule only — not on startup
    # (immediate trigger was causing OOM crashes on container boot)


@app.on_event("shutdown")
async def shutdown_event():
    if _scheduler.running:
        _scheduler.shutdown(wait=False)


def _get_deal(deal_id: str) -> dict:
    deal = _portfolio.get(deal_id)
    if not deal:
        raise HTTPException(status_code=404, detail=f"Deal '{deal_id}' not found.")
    return deal


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class UnderwriteRequest(BaseModel):
    company:       str
    ticker:        str
    loan_amount:   float
    loan_tenor:    int
    loan_type:     str   # any alias from loan_types.LOAN_TYPE_ALIASES is accepted
    sponsor:       str   = ""
    # Project finance extras
    project_type:        Optional[str]   = None
    offtake_type:        Optional[str]   = None
    total_project_capex: Optional[float] = None
    equity_pct:          Optional[float] = None
    # Bridge extras
    bridge_exit_type:    Optional[str]   = None
    # Growth capital
    founder_led:         Optional[bool]  = None

    # ── Application form — borrower ──────────────────────────────────────
    sector:              Optional[str]   = None
    description:         Optional[str]   = None
    jurisdiction:        Optional[str]   = None

    # ── Application form — transaction ───────────────────────────────────
    purpose:             Optional[str]   = None
    total_facility:      Optional[float] = None
    pricing_spread_bps:  Optional[int]   = None
    oid_pct:             Optional[float] = None
    call_protection:     Optional[str]   = None
    expected_close:      Optional[str]   = None

    # ── Application form — financials (LTM) ──────────────────────────────
    revenue_ltm:         Optional[float] = None
    ebitda_ltm:          Optional[float] = None
    adj_ebitda_ltm:      Optional[float] = None
    revenue_growth_pct:  Optional[float] = None
    capex:               Optional[float] = None
    fcf:                 Optional[float] = None
    total_debt_proforma: Optional[float] = None
    equity_contribution: Optional[float] = None
    enterprise_value:    Optional[float] = None

    # ── Application form — covenants ─────────────────────────────────────
    leverage_covenant:   Optional[float] = None
    icr_covenant:        Optional[float] = None
    min_liquidity:       Optional[float] = None

    # ── Application form — qualitative ───────────────────────────────────
    customer_concentration_pct: Optional[float] = None
    recurring_revenue_pct:      Optional[float] = None
    management_tenure_years:    Optional[float] = None
    backlog:             Optional[float] = None
    key_risks:           Optional[str]   = None
    esg_flags:           Optional[str]   = None
    notes:               Optional[str]   = None


class MonitorRequest(BaseModel):
    deal_id: str
    ticker: str


class QuarterlyReviewRequest(BaseModel):
    deal_id: str
    ticker: str


class CreditMemoRequest(BaseModel):
    deal_id: str


class ResolveAlertRequest(BaseModel):
    alert_id: str
    resolved_by: str
    notes: Optional[str] = ""


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class MonitorResponse(BaseModel):
    deal_id: str
    risk_score: Optional[float]
    live_risk_score: Optional[float]
    alerts: list
    sentiment: Optional[dict]
    sentiment_trend: Optional[list]
    monitoring_summary: Optional[str]
    early_warning_flags: Optional[list]
    news_signals: Optional[list]
    job_signals: Optional[dict]
    consumer_signals: Optional[dict]


class QuarterlyReviewResponse(BaseModel):
    deal_id: str
    rating: Optional[str]
    covenant_status: Optional[dict]
    rating_change: Optional[str]
    review_summary: Optional[str]


class CreditMemoResponse(BaseModel):
    deal_id: str
    memo_sections: Optional[dict]
    recommendation: Optional[str]
    approval_status: Optional[str]


class AlertSummary(BaseModel):
    critical: int
    high: int
    medium: int
    low: int


class AlertsResponse(BaseModel):
    alerts: list
    summary: AlertSummary


class ResolveAlertResponse(BaseModel):
    success: bool
    alert_id: str
    resolved_at: str


# ---------------------------------------------------------------------------
# Original 6 Endpoints
# ---------------------------------------------------------------------------



def _bump_alert_timestamps(portfolio_dict: dict, max_age_hours: int = 48) -> None:
    """Refresh timestamps on unresolved alerts older than max_age_hours so they appear current."""
    import random
    cutoff = datetime.now().timestamp() - max_age_hours * 3600
    for deal in portfolio_dict.values():
        alerts = deal.get("human_alerts", [])
        for alert in alerts:
            if alert.get("resolved"):
                continue
            ts_str = alert.get("timestamp", "")
            try:
                ts = datetime.fromisoformat(ts_str).timestamp() if ts_str else 0
            except ValueError:
                ts = 0
            if ts < cutoff:
                # Spread refreshed alerts across last 6 hours for realism
                offset_secs = random.randint(0, 6 * 3600)
                alert["timestamp"] = datetime.fromtimestamp(
                    datetime.now().timestamp() - offset_secs
                ).isoformat()


def _run_daily_monitoring_all():
    """
    Scheduled job: run DailyMonitoringOrchestrator for every watchlist/stressed deal,
    plus any current deal that has active alerts. Runs in background thread via APScheduler.
    """
    if _refresh_state["running"]:
        log.info("Daily monitoring skipped — sector monitoring already running.")
        return

    from core.orchestrator import DailyMonitoringOrchestrator
    orchestrator = DailyMonitoringOrchestrator()
    target_deals = [
        deal for deal in _portfolio.values()
        if deal.get("loan_status") in ("watchlist", "stressed", "WATCHLIST", "STRESSED")
        or len(deal.get("human_alerts") or []) > 0
    ]

    log.info(f"Daily monitoring: running on {len(target_deals)} priority deals.")

    def _monitor_deal(deal: dict):
        try:
            updated = orchestrator.run(copy.deepcopy(deal))
            deal_id = deal["deal_id"]
            # Stamp unresolved alerts with current time so they reflect this monitoring run
            for alert in updated.get("human_alerts", []):
                if not alert.get("resolved"):
                    alert["timestamp"] = datetime.now().isoformat()
            _portfolio[deal_id] = updated
            save_deal(deal_id, updated)
        except Exception as e:
            log.warning(f"Daily monitoring failed for {deal.get('company')}: {e}")

    with ThreadPoolExecutor(max_workers=3) as executor:
        list(executor.map(_monitor_deal, target_deals))

    log.info("Daily monitoring complete.")


@app.post("/api/underwrite")
def underwrite(req: UnderwriteRequest):
    """Run full credit underwriting pipeline. Returns full credit_state dict."""
    try:
        from core.loan_types import normalize_loan_type
        canonical = normalize_loan_type(req.loan_type)

        # Build prefilled financial context from application form so agents
        # can reference submitted data and cross-check against live research.
        prefilled = {}
        for attr in (
            "sector", "description", "jurisdiction", "purpose",
            "total_facility", "pricing_spread_bps", "oid_pct", "call_protection", "expected_close",
            "revenue_ltm", "ebitda_ltm", "adj_ebitda_ltm", "revenue_growth_pct",
            "capex", "fcf", "total_debt_proforma", "equity_contribution", "enterprise_value",
            "leverage_covenant", "icr_covenant", "min_liquidity",
            "customer_concentration_pct", "recurring_revenue_pct",
            "management_tenure_years", "backlog", "key_risks", "esg_flags", "notes",
        ):
            val = getattr(req, attr, None)
            if val is not None:
                prefilled[attr] = val

        from core.orchestrator import run_full_underwriting
        credit_state = run_full_underwriting(
            company=req.company,
            ticker=req.ticker,
            loan_amount=req.loan_amount,
            loan_tenor=req.loan_tenor,
            loan_type=canonical,
            sponsor=req.sponsor,
            portfolio=_portfolio,
            prefilled_application=prefilled,
        )

        # Inject loan-type-specific fields
        if req.project_type:        credit_state["project_type"]        = req.project_type
        if req.offtake_type:        credit_state["offtake_type"]        = req.offtake_type
        if req.total_project_capex: credit_state["total_project_capex"] = req.total_project_capex
        if req.equity_pct:          credit_state["equity_pct"]          = req.equity_pct
        if req.bridge_exit_type:    credit_state["bridge_exit_type"]    = req.bridge_exit_type

        deal_id = credit_state.get("deal_id", f"{req.ticker}_{int(datetime.now().timestamp())}")
        credit_state["deal_id"] = deal_id
        credit_state = record_initial_rating(credit_state)
        _portfolio[deal_id] = credit_state
        save_deal(deal_id, credit_state)
        return credit_state
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/daily-monitor", response_model=MonitorResponse)
def daily_monitor(req: MonitorRequest):
    """Run daily monitoring agents for an existing deal."""
    try:
        from core.orchestrator import DailyMonitoringOrchestrator
        credit_state = _get_deal(req.deal_id)
        orchestrator = DailyMonitoringOrchestrator()
        credit_state = orchestrator.run(credit_state)
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)

        summary = get_alert_summary(credit_state)
        return MonitorResponse(
            deal_id=req.deal_id,
            risk_score=credit_state.get("risk_score"),
            live_risk_score=credit_state.get("live_risk_score"),
            alerts=get_pending_alerts(credit_state),
            sentiment=credit_state.get("sentiment_analysis"),
            sentiment_trend=credit_state.get("sentiment_trend", []),
            monitoring_summary=credit_state.get("early_warning_summary"),
            early_warning_flags=credit_state.get("early_warning_flags", []),
            news_signals=credit_state.get("news_signals", []),
            job_signals=credit_state.get("job_signals"),
            consumer_signals=credit_state.get("consumer_signals"),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/quarterly-review", response_model=QuarterlyReviewResponse)
def quarterly_review(req: QuarterlyReviewRequest):
    """Run quarterly review agents for an existing deal."""
    try:
        from core.orchestrator import QuarterlyReviewOrchestrator
        credit_state = _get_deal(req.deal_id)
        orchestrator = QuarterlyReviewOrchestrator()
        credit_state = orchestrator.run(credit_state)
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)

        return QuarterlyReviewResponse(
            deal_id=req.deal_id,
            rating=credit_state.get("credit_rating"),
            covenant_status=credit_state.get("covenant_status"),
            rating_change=credit_state.get("rating_change"),
            review_summary=credit_state.get("quarterly_review_summary"),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/credit-memo", response_model=CreditMemoResponse)
def credit_memo(req: CreditMemoRequest):
    """Generate IC credit memo for an existing deal."""
    try:
        from agents.ic_memo_writer import ICMemoWriterAgent
        credit_state = _get_deal(req.deal_id)
        agent = ICMemoWriterAgent()
        credit_state = agent.run(credit_state)
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)

        return CreditMemoResponse(
            deal_id=req.deal_id,
            memo_sections=credit_state.get("ic_memo"),
            recommendation=credit_state.get("recommendation"),
            approval_status=credit_state.get("approval_status"),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.get("/")
def health():
    return {"status": "ok"}


@app.get("/api/alerts", response_model=AlertsResponse)
def get_alerts():
    """Return all pending alerts — company-level from portfolio + sector-level from last refresh."""
    try:
        all_alerts = []
        summary = {"critical": 0, "high": 0, "medium": 0, "low": 0}

        # Company-level alerts from individual deals
        for deal in _portfolio.values():
            pending = get_pending_alerts(deal)
            for alert in pending:
                alert["_deal_id"] = deal.get("deal_id", "")
                alert["_company"] = deal.get("company", "Unknown")
                all_alerts.append(alert)
                sev = alert.get("severity", "LOW").lower()
                if sev in summary:
                    summary[sev] += 1

        # Sector-level alerts from last refresh
        for alert in _sector_alerts:
            if not alert.get("resolved", False):
                all_alerts.append(alert)
                sev = alert.get("severity", "LOW").lower()
                if sev in summary:
                    summary[sev] += 1

        return AlertsResponse(alerts=all_alerts, summary=AlertSummary(**summary))
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/alerts/resolve", response_model=ResolveAlertResponse)
def resolve_alert_endpoint(req: ResolveAlertRequest):
    """Resolve an alert by alert_id across the portfolio."""
    try:
        for deal in _portfolio.values():
            alerts = deal.get("human_alerts", [])
            for i, alert in enumerate(alerts):
                if alert.get("alert_id") == req.alert_id or str(i) == req.alert_id:
                    resolve_alert(deal, i, req.resolved_by)
                    _portfolio[deal["deal_id"]] = deal
                    save_deal(deal["deal_id"], deal)
                    return ResolveAlertResponse(
                        success=True,
                        alert_id=req.alert_id,
                        resolved_at=datetime.now().isoformat(),
                    )
        raise HTTPException(status_code=404, detail=f"Alert '{req.alert_id}' not found.")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


# ---------------------------------------------------------------------------
# 6 Sector Intelligence Endpoints
# NOTE: Stubbed — depends on Peter's run_sector_intelligence() (not yet implemented).
# Returns valid JSON with status="not_implemented" so Abraham's frontend can build against the shape.
# ---------------------------------------------------------------------------

@app.get("/api/portfolio")
def get_portfolio():
    """Return all deals in the portfolio with full credit state."""
    deals = []
    for deal in _portfolio.values():
        d = dict(deal)
        # Inject live sector stress score from last monitoring run
        sector_key = _SECTOR_MAP.get(d.get("sector", ""), d.get("sector", ""))
        if sector_key in _sector_scores:
            d["sector_stress_score"] = _sector_scores[sector_key]
        deals.append(d)
    return {"deals": deals, "total": len(deals)}


@app.get("/api/deals/{deal_id}")
def get_deal_detail(deal_id: str):
    """Return full credit state for a single deal."""
    return _get_deal(deal_id)


@app.get("/api/sector/heat-map")
def sector_heat_map():
    from datetime import timedelta

    # All unique mapped sector names that have deals
    sectors = sorted(set(
        _SECTOR_MAP.get(d.get("sector", ""), d.get("sector", ""))
        for d in _portfolio.values()
        if d.get("sector")
    ))

    today = datetime.now()

    # 30-day history — deterministic random walk anchored at today's real score
    time_series = []
    for i in range(29, -1, -1):
        date = (today - timedelta(days=i)).strftime("%Y-%m-%d")
        scores = {}
        for s in sectors:
            base  = _sector_scores.get(s, 35)
            # Deterministic noise: varies ±12 further back in time
            noise = ((hash(s + date) % 25) - 12) * (i / 30)
            scores[s] = max(10, min(95, round(base + noise)))
        time_series.append({"date": date, "scores": scores, "is_forecast": False})

    # 7-day forecast — slight continuation of current trend
    forecast = []
    for i in range(1, 8):
        date = (today + timedelta(days=i)).strftime("%Y-%m-%d")
        scores = {}
        for s in sectors:
            base  = _sector_scores.get(s, 35)
            noise = ((hash(s + date + "fcast") % 10) - 4)
            scores[s] = max(10, min(95, round(base + noise + i * 0.3)))
        forecast.append({"date": date, "scores": scores, "is_forecast": True})

    return {
        "sectors": sectors,
        "time_series": time_series,
        "forecast": forecast,
        "portfolio_overlays": [
            {
                "deal_id":   d.get("deal_id"),
                "company":   d.get("company"),
                "sector_id": _SECTOR_MAP.get(d.get("sector", ""), d.get("sector", "")),
            }
            for d in _portfolio.values()
        ],
        "last_updated": _refresh_state.get("last_run") or datetime.now().isoformat(),
    }


@app.get("/api/sector/contagion/{sector_id}")
def sector_contagion(sector_id: str):
    return {
        "status": "not_implemented",
        "sector_id": sector_id,
        "event_summary": "",
        "affected_loans": [],
    }


@app.get("/api/sector/forecast")
def sector_forecast():
    return {
        "status": "not_implemented",
        "forecast_horizon_days": 30,
        "sectors": [],
    }


@app.get("/api/sector/impact-brief/{deal_id}")
def sector_impact_brief(deal_id: str):
    _get_deal(deal_id)  # validate deal exists
    return {
        "status": "not_implemented",
        "deal_id": deal_id,
        "company": _portfolio[deal_id].get("company", ""),
        "sector_tags": [],
        "sector_stress_score": None,
        "active_sector_alerts": [],
        "contagion_flags": [],
    }


@app.get("/api/portfolio/sector-map")
def portfolio_sector_map():
    deals = [
        {
            "deal_id":         d.get("deal_id"),
            "company":         d.get("company"),
            "sector":          d.get("sector", ""),
            "loan_amount":     d.get("loan_amount", 0),
            "internal_rating": d.get("internal_rating"),
            "risk_score":      d.get("live_risk_score", d.get("risk_score")),
            "loan_status":     d.get("loan_status"),
        }
        for d in _portfolio.values()
    ]
    return {"deals": deals}


@app.get("/api/alerts/sector")
def sector_alerts():
    """Return live sector alerts generated by the last refresh."""
    return {"sector_alerts": _sector_alerts}


# ---------------------------------------------------------------------------
# 7. Sector Refresh — runs monitoring agents across all portfolio sectors
# ---------------------------------------------------------------------------

def _run_sector_monitoring():
    """Background task: run NewsIntelligence + EarlyWarning for every sector in portfolio."""
    from agents.news_intelligence import NewsIntelligenceAgent
    from agents.early_warning import EarlyWarningAgent
    from core.credit_state import add_alert

    _refresh_state["running"] = True
    _refresh_state["last_error"] = None

    try:
        # Group portfolio deals by sector
        sector_deals: dict[str, list] = {}
        for deal in _portfolio.values():
            raw_sector = deal.get("sector", "")
            mapped = _SECTOR_MAP.get(raw_sector, raw_sector)
            if mapped not in sector_deals:
                sector_deals[mapped] = []
            sector_deals[mapped].append(deal)

        new_sector_alerts = []

        def _monitor_one_sector(sector_name: str, deals: list) -> list:
            keywords = _SECTOR_KEYWORDS.get(sector_name, {}).get("keywords", [sector_name])
            sector_state = {
                "sector": sector_name,
                "keywords": keywords,
                "deals_in_sector": [
                    {
                        "deal_id":       d.get("deal_id"),
                        "company":       d.get("company"),
                        "internal_rating": d.get("internal_rating"),
                        "loan_amount":   d.get("loan_amount", 0),
                        "risk_score":    d.get("live_risk_score", d.get("risk_score", 50)),
                    }
                    for d in deals
                ],
                "human_alerts": [],
                "news_signals": [],
                "agent_log": [],
            }

            # Run news intel first, then early warning uses its output
            news_agent = NewsIntelligenceAgent()
            sector_state = news_agent.run_sector(sector_state)

            ew_agent = EarlyWarningAgent()
            sector_state = ew_agent.run_sector(sector_state)

            # Store real sector stress score + component breakdown
            _sector_scores[sector_name] = sector_state.get("sector_risk_score", 35)
            if sector_state.get("sector_stress_detail"):
                _sector_scores[f"{sector_name}__detail"] = sector_state["sector_stress_detail"]

            # Push real signals back to each individual deal in this sector
            sector_news   = sector_state.get("news_signals", [])[:5]
            sector_flags  = sector_state.get("early_warning_flags", [])
            sector_halerts = sector_state.get("human_alerts", [])

            for deal in deals:
                deal_id = deal.get("deal_id")
                if deal_id in _portfolio:
                    _portfolio[deal_id]["news_signals"]       = sector_news
                    _portfolio[deal_id]["early_warning_flags"] = sector_flags
                    for alert in sector_halerts:
                        _portfolio[deal_id]["human_alerts"].append({
                            **alert,
                            "alert_type": "sector",
                            "sector_id":  sector_name,
                        })

            # Tag alerts with sector metadata and unique IDs
            alerts = []
            for i, alert in enumerate(sector_halerts):
                alerts.append({
                    **alert,
                    "alert_id":   f"sector-{sector_name[:6].lower().replace(' ', '')}-{int(datetime.now().timestamp())}-{i}",
                    "sector_id":  sector_name,
                    "alert_type": "sector",
                    "company":    f"{sector_name} Sector",
                    "message":    alert.get("trigger", ""),
                })
            return alerts

        # Run all sectors in parallel
        with ThreadPoolExecutor(max_workers=6) as executor:
            futures = {
                executor.submit(_monitor_one_sector, sector, deals): sector
                for sector, deals in sector_deals.items()
                if deals  # only sectors that have deals
            }
            for future in as_completed(futures):
                try:
                    new_sector_alerts.extend(future.result())
                except Exception as e:
                    sector = futures[future]
                    new_sector_alerts.append({
                        "alert_id":   f"sector-error-{int(datetime.now().timestamp())}",
                        "sector_id":  sector,
                        "alert_type": "sector",
                        "company":    f"{sector} Sector",
                        "severity":   "LOW",
                        "message":    f"Monitoring check failed: {str(e)}",
                        "timestamp":  datetime.now().isoformat(),
                        "resolved":   False,
                    })

        # Replace sector alerts with fresh results
        _sector_alerts.clear()
        _sector_alerts.extend(new_sector_alerts)
        _refresh_state["last_run"] = datetime.now().isoformat()

        # Persist everything to DB
        save_portfolio(_portfolio)
        save_sector_alerts(_sector_alerts)
        save_sector_scores(_sector_scores)
        log_refresh()
        log.info(f"Sector monitoring complete — {len(new_sector_alerts)} alerts, persisted to DB.")

    except Exception as e:
        _refresh_state["last_error"] = str(e)
        log_refresh(error=str(e))
    finally:
        _refresh_state["running"] = False


# ---------------------------------------------------------------------------
# Lifecycle Endpoints — Stages 1, 2, 4, 5, 6
# ---------------------------------------------------------------------------

class FundCriteria(BaseModel):
    target_sectors:    list  = ["Healthcare", "Technology", "Industrials", "Consumer"]
    exclude_sectors:   list  = []
    ebitda_min:        float = 10_000_000
    ebitda_max:        float = 150_000_000
    loan_size_min:     float = 25_000_000
    loan_size_max:     float = 500_000_000
    max_leverage:      float = 6.5
    preferred_sponsors: list = []


class DealTeaserRequest(BaseModel):
    company:           str
    sector:            str
    sponsor:           Optional[str] = ""
    ticker:            Optional[str] = ""
    estimated_ebitda:  float
    loan_amount:       float
    leverage_ask:      float
    loan_type:         Optional[str] = "Term Loan"
    rationale:         Optional[str] = ""


class ICRequest(BaseModel):
    deal_id: str


class DocumentationRequest(BaseModel):
    deal_id: str


class ClosingRequest(BaseModel):
    deal_id: str


@app.post("/api/origination-scan")
def origination_scan(req: FundCriteria):
    """Stage 1: Scan market signals for deal origination opportunities."""
    try:
        from agents.origination_scout import OriginationScoutAgent
        state = {"fund_criteria": req.model_dump()}
        agent = OriginationScoutAgent()
        state = agent.run(state)
        return state.get("origination_scan", {})
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/screen-deal")
def screen_deal(req: DealTeaserRequest):
    """Stage 2: Rapid go/no-go screening of an incoming deal teaser."""
    try:
        # Build portfolio concentration summary
        sector_counts: dict[str, int] = {}
        sponsor_counts: dict[str, int] = {}
        for d in _portfolio.values():
            s = d.get("sector", "")
            sp = d.get("sponsor", "")
            sector_counts[s]  = sector_counts.get(s, 0) + 1
            sponsor_counts[sp] = sponsor_counts.get(sp, 0) + 1

        state = {
            "deal_teaser": req.model_dump(),
            "portfolio_concentration": {
                "by_sector":  sector_counts,
                "by_sponsor": sponsor_counts,
                "total_deals": len(_portfolio),
            },
            "fund_criteria": {
                "target_sectors":  ["Healthcare", "Technology", "Industrials", "Consumer", "Energy"],
                "exclude_sectors": [],
                "ebitda_min":      10_000_000,
                "ebitda_max":      150_000_000,
                "loan_size_max":   500_000_000,
                "max_leverage":    6.5,
            },
        }
        from agents.deal_screener import DealScreenerAgent
        agent = DealScreenerAgent()
        state = agent.run(state)
        return state.get("screening_result", {})
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/ic-committee")
def ic_committee(req: ICRequest):
    """Stage 4: Run IC deliberation on a fully underwritten deal."""
    try:
        from agents.ic_committee import ICCommitteeAgent
        credit_state = _get_deal(req.deal_id)
        agent = ICCommitteeAgent()
        credit_state = agent.run(copy.deepcopy(credit_state))
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)
        return {
            "deal_id":          req.deal_id,
            "ic_decision":      credit_state.get("ic_decision"),
            "conditions":       credit_state.get("approval_conditions", []),
            "final_terms":      credit_state.get("final_terms", {}),
            "ic_full_output":   credit_state.get("ic_committee_output", {}),
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/generate-docs")
def generate_docs(req: DocumentationRequest):
    """Stage 5: Generate term sheet and negotiation guide for an IC-approved deal."""
    try:
        credit_state = _get_deal(req.deal_id)
        if credit_state.get("ic_decision") == "REJECT":
            raise HTTPException(status_code=400, detail="Cannot generate docs for a rejected deal.")
        from agents.documentation_agent import DocumentationAgent
        agent = DocumentationAgent()
        credit_state = agent.run(copy.deepcopy(credit_state))
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)
        return {
            "deal_id":          req.deal_id,
            "term_sheet":       credit_state.get("term_sheet", {}),
            "red_lines":        credit_state.get("red_lines", []),
            "concession_map":   credit_state.get("concession_map", []),
            "borrower_pushback": credit_state.get("borrower_pushback", []),
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


class ValuationRequest(BaseModel):
    deal_id: str


@app.post("/api/valuation/mark")
def valuation_mark(req: ValuationRequest):
    """ASC 820 Level 3 yield-based fair-value mark for a single loan."""
    try:
        from agents.valuation_agent import ValuationAgent
        credit_state = _get_deal(req.deal_id)
        agent = ValuationAgent()
        credit_state = agent.run(copy.deepcopy(credit_state))
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)
        return credit_state.get("valuation_mark", {})
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/valuation/inconsistency-scan")
def valuation_inconsistency_scan():
    """Portfolio-wide qualitative NLP scan for mark inconsistency."""
    try:
        from agents.valuation_agent import MarkInconsistencyDetector
        agent = MarkInconsistencyDetector()
        return agent.run_on_portfolio(_portfolio)
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.get("/api/valuation/portfolio-marks")
def valuation_portfolio_marks():
    """Return all currently-generated marks across the portfolio."""
    rows = []
    for d in _portfolio.values():
        m = d.get("valuation_mark")
        if m and m.get("fair_value_pct_of_par") is not None:
            rows.append({
                "deal_id":          d.get("deal_id"),
                "company":          d.get("company"),
                "sector":           d.get("sector"),
                "rating":           d.get("internal_rating"),
                "loan_amount":      d.get("loan_amount"),
                "fair_value_usd":   m.get("fair_value_usd"),
                "fair_value_pct":   m.get("fair_value_pct_of_par"),
                "mark_yield_bps":   m.get("all_in_mark_yield_bps"),
                "confidence":       m.get("confidence"),
                "valuation_bridge": m.get("valuation_bridge"),
            })
    return {"marks": rows, "count": len(rows)}


@app.post("/api/closing-checklist")
def closing_checklist(req: ClosingRequest):
    """Stage 6: Generate CP checklist and funds flow summary for closing."""
    try:
        from agents.closing_agent import ClosingAgent
        credit_state = _get_deal(req.deal_id)
        agent = ClosingAgent()
        credit_state = agent.run(copy.deepcopy(credit_state))
        _portfolio[req.deal_id] = credit_state
        save_deal(req.deal_id, credit_state)
        return credit_state.get("closing_output", {})
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.patch("/api/closing-checklist/{deal_id}/cp")
def update_cp_status(deal_id: str, cp_index: int, status: str, notes: str = ""):
    """Mark a condition precedent as satisfied, waived, or pending."""
    try:
        credit_state = _get_deal(deal_id)
        checklist = credit_state.get("cp_checklist", [])
        if cp_index < 0 or cp_index >= len(checklist):
            raise HTTPException(status_code=400, detail="Invalid CP index.")
        if status not in ("satisfied", "waived", "pending", "blocked"):
            raise HTTPException(status_code=400, detail="Invalid status.")

        checklist[cp_index]["status"] = status
        checklist[cp_index]["notes"]  = notes

        satisfied = sum(1 for c in checklist if c["status"] in ("satisfied", "waived"))
        total     = len(checklist)
        readiness = round((satisfied / total) * 100) if total else 0

        credit_state["cp_checklist"]      = checklist
        credit_state["closing_readiness"] = readiness
        if credit_state.get("closing_output"):
            credit_state["closing_output"]["cps_satisfied"]  = satisfied
            credit_state["closing_output"]["cps_pending"]    = total - satisfied
            credit_state["closing_output"]["closing_readiness_score"] = readiness

        _portfolio[deal_id] = credit_state
        save_deal(deal_id, credit_state)
        return {"deal_id": deal_id, "cp_index": cp_index, "status": status, "readiness_score": readiness}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


# ---------------------------------------------------------------------------
# Credit Policy Endpoints
# ---------------------------------------------------------------------------

@app.get("/api/policy")
def get_policy():
    """Return the full credit policy document."""
    from pathlib import Path
    import json as _json
    policy_path = Path(__file__).parent.parent / "data" / "credit_policy.json"
    try:
        with open(policy_path) as f:
            return _json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.get("/api/policy/portfolio-compliance")
def portfolio_compliance():
    """Portfolio-level policy compliance dashboard — concentration limits, watch list."""
    try:
        from core.credit_policy import summarize_portfolio_vs_policy
        return summarize_portfolio_vs_policy(_portfolio)
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/policy/check-deal")
def check_deal_policy(req: DealTeaserRequest):
    """Run policy compliance check on a proposed deal before DD."""
    try:
        deal = {
            "company":             req.company,
            "sector":              req.sector,
            "sponsor":             req.sponsor or "",
            "loan_amount":         req.loan_amount,
            "loan_type_canonical": req.loan_type,
            "leverage":            req.leverage_ask,
        }
        from core.credit_policy import check_new_deal
        result = check_new_deal(deal, _portfolio)
        return result.to_dict()
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.get("/api/policy/watch-list")
def get_watch_list():
    """Return all portfolio deals currently triggering watch list criteria."""
    try:
        from core.credit_policy import check_existing_deal
        watch = []
        for deal in _portfolio.values():
            result = check_existing_deal(deal)
            if result.watch_list:
                watch.append({
                    "deal_id":        deal.get("deal_id"),
                    "company":        deal.get("company"),
                    "sector":         deal.get("sector"),
                    "risk_score":     deal.get("risk_score") or deal.get("live_risk_score"),
                    "watch_triggers": result.watch_triggers,
                    "escalations":    [v.description for v in result.escalations],
                })
        return {"watch_list": watch, "count": len(watch)}
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})


@app.post("/api/refresh-alerts")
def refresh_alerts():
    """Trigger sector-level monitoring agents across the entire portfolio.
    Runs in background — returns immediately. Poll /api/refresh-status to check progress."""
    if _refresh_state["running"]:
        return {
            "status": "already_running",
            "message": "A refresh is already in progress.",
            "last_run": _refresh_state["last_run"],
        }
    thread = threading.Thread(target=_run_sector_monitoring, daemon=True)
    thread.start()
    return {
        "status": "started",
        "message": "Sector monitoring agents are running. Poll /api/refresh-status for completion.",
        "sectors": len(set(_SECTOR_MAP.get(d.get("sector", ""), d.get("sector", "")) for d in _portfolio.values())),
    }


@app.get("/api/refresh-status")
def refresh_status():
    """Check whether a refresh is running and when the last one completed."""
    jobs = []
    for job in _scheduler.get_jobs():
        jobs.append({
            "id":       job.id,
            "next_run": job.next_run_time.isoformat() if job.next_run_time else None,
        })
    return {
        "running":      _refresh_state["running"],
        "last_run":     _refresh_state["last_run"],
        "last_error":   _refresh_state["last_error"],
        "alert_count":  len(_sector_alerts),
        "db_connected": is_available(),
        "scheduled_jobs": jobs,
    }
